### PR TITLE
updates to organization on service builder and draft of permissions

### PR DESCRIPTION
**Pull request by stephenkostas**

### CODE REVIEW

**Comment by stephenkostas** [comment]
@sez11a - I created a short section on placing all of the messaging into the portlet java files, but it looks like as it stands, we don't actually use any of it in the JSP until we get to the UI section towards the end? I left the section ambiguously named until we can sort that out.

**Comment by sez11a** [comment]
@stephenkostas The section should also cover putting the tags in the JSP files. The point is to surface the messages to the user rather than bury them in the logs.

**Comment by stephenkostas** [comment]
Okay. I'll add them to the JSPs there then as well.

**Comment by stephenkostas** [comment]
Section has been updated with feedback, including Language.properties.

**Comment by sez11a** [comment]
Closing now as tracking these changes in another branch.

**Pull request closed without merging**
