### PR TITLE
LRDOCS-3678 layout template look and feel

### PR DESCRIPTION
**Pull request by mwilliams2014**
cc @blzaugg

### CODE REVIEW

**Comment by blzaugg** [comment]
I feel like readers would be better served if we created a, simple, custom layout template file and included it in the theme. Rather that use one of Porygon's.

**Comment by blzaugg** [comment]
Why not use this one: https://github.com/sez11a/liferay-docs/pull/2500/commits/fdf7c3f3ae1178d0fc57d7707a9f67a5413ec3d8#diff-c0a12095c4c7cfb3964fe8374db27c49R111

**Comment by mwilliams2014** [comment]
Good point @blzaugg. It makes more sense to stick to one example throughout. I'll update the pull and push the changes. Thx!

**Comment by blzaugg** [comment]
LGTM

**Pull request merged**
