### PR TITLE
OSGi Portlets by Example

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by sez11a** [comment]
@jrao, can you review this? Thanks!

**Comment by jrao** [comment]
@sez11a Reviewing now

**Comment by jrao** [comment]
@rotty3000 Hi Ray, when I follow the steps of your OSGi Portlets by Example document, I'm able to deploy the module to Liferay but I can't add the portlet to a page. I can see the bundle when I run "lb" from the Gogo shell, but when I click *Add Applications* from a Liferay page, the portlet does not appear in the Add Applications menu. Same situation with the Portlet DS portlet from the blade project.

Is this because there are no JSPs in the project? The end of the OSGi Portlets by Example document suggests that the project should be able to be added to a page.

https://github.com/rotty3000/liferay-docs/blob/4fd86a7e91724d66ba49b22afc9d2d30ddd93ac4/develop/new-articles/osgi-portlets-by-example.markdown

**Comment by rotty3000** [comment]
Which version of Liferay are you using?

Are you using the latest blade project?

You don't need JSPs but your portlet should output something so you know
it's executing properly.

We have 40-50 working portlets in master using this so I'm not clear why
it's not working for you. Perhaps we can setup a debug session in the next
couple of days so I can help clarify some diagnostics stuff. this might be
good for your documentation as well.

- Ray

On Tue, Mar 3, 2015 at 3:48 PM, Jesse Rao <notifications@github.com> wrote:

> @rotty3000 <https://github.com/rotty3000> Hi Ray, when I follow the steps
> of your OSGi Portlets by Example document, I'm able to deploy the module to
> Liferay but I can't add the portlet to a page. I can see the bundle when I
> run "lb" from the Gogo shell, but when I click *Add Applications* from a
> Liferay page, the portlet does not appear in the Add Applications menu.
> Same situation with the Portlet DS portlet from the blade project.
>
> Is this because there are no JSPs in the project? The end of the OSGi
> Portlets by Example document suggests that the project should be able to be
> added to a page.
>
>
> https://github.com/rotty3000/liferay-docs/blob/4fd86a7e91724d66ba49b22afc9d2d30ddd93ac4/develop/new-articles/osgi-portlets-by-example.markdown
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sez11a/liferay-docs/pull/1073#issuecomment-77031189>.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by jrao** [comment]
@rotty3000 I'm using Liferay 6.2 CE GA3 and the lastest blade project.

Setting up a debug session would be great. Let me know whatever time works best for you.

**Comment by rotty3000** [comment]
Portlets from blade don't work in that release.

Everything documented in this document is for Liferay 7.0

On Tue, Mar 3, 2015 at 4:08 PM, Jesse Rao <notifications@github.com> wrote:

> @rotty3000 <https://github.com/rotty3000> I'm using Liferay 6.2 CE GA3
> and the lastest blade project.
>
> Setting up a debug session would be great. Let me know whatever time works
> best for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sez11a/liferay-docs/pull/1073#issuecomment-77034841>.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by sez11a** [comment]
Sorry, @jrao; I should have told you that. This is a Liferay 7 pull.

**Comment by jrao** [comment]
Ah, ok. Thanks for clarifying.

**Comment by sez11a** [comment]
Thank you Ray; this is now superseded by #1209.

**Pull request closed without merging**
