### PR TITLE
LRDOCS-3365

### PR DESCRIPTION
**Pull request by justinchoi001**

### CODE REVIEW

**Comment by mhan810** [comment]
@justinchoi001 this needs to rephrased.  This would only apply if a customer knows that they have clustered nodes deployed to different networks.  By setting this, this will allow clustered nodes that are deployed to separate networks (e.g. separated by different firewalls) to communicate together.  If customers are not deploying clustered nodes to separate networks, then this is irrelevant and could cause more InfoSec audits.

**Comment by justinchoi001** [comment]
@mhan810 ,

Thanks for your help! I will definitely incorporate your comments.

**Comment by justinchoi001** [comment]
@mhan810 @sez11a , the document has been updated per Mike's comment.

**Comment by sez11a** [comment]
Hey @justinchoi001 I think this needs more clarification. It sounds like you're recommending that if you have this topology, where you have locally clustered nodes and nodes on other networks, that you have to set this on all the nodes. Wouldn't it be better to define particular nodes to talk to the other networks, and then set this only on those nodes? Not sure; just asking. @mhan810

**Comment by sez11a** [comment]
View total diff: https://github.com/sez11a/liferay-docs/compare/628c2d61e6...d3672a269c

**Pull request closed without merging**
