### PR TITLE
LRDOCS-1974 Liferay 7 Upgrade documentation

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by vicnate5** [comment]
@sez11a @achaparro 

There is an additional update needed to this documentation.

The index property must be set to **false** after upgrade.

Instead of 
```
Once you have upgraded your portal, remove this property or set it to
 `false` so that you can index all objects from Liferay's Control Panel.
```

This should note:
```
Once you have upgraded your portal, make sure to set this property to
 `false` so that you can index all objects from Liferay's Control Panel.
```

See comment here https://issues.liferay.com/browse/LPS-65253#comment-765309

CC @jrhoun

**Comment by achaparro** [comment]
Done @vicnate5!

Thanks.

**Comment by sez11a** [comment]
Started reviewing. :-)

**Comment by sez11a** [comment]
Superseded by https://github.com/achaparro/liferay-docs/pull/3

**Pull request closed without merging**
