### PR TITLE
LRDOCS-3789 JSF Project Wizard in IDE

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.liferay.com/browse/LRDOCS-3789

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @codyhoag I think this should be broken into two smaller articles: 

1. Generating a project from Maven
2. Generating a project from IDE

It sort of sounds awkward to transition between the two in one article by saying "Great! You've generated a project on the command line; now you'll learn to generate a project in IDE!" Nobody works that way; they want to generate their project and move on. 

Can you break this up? Thanks!

**Comment by codyhoag** [comment]
@sez11a Yeah, good point. I'll break it up.

I think it would make more sense to title the first article *Generating a Project from the Command Line*. Although JSF projects are generated using Maven archetypes, they generate a `build.gradle` file to cater to developers who prefer Gradle. Therefore, keeping it generic would lure those developers to read the article too. What do you think?

**Comment by sez11a** [comment]
@codyhoag Sounds good to me!

**Comment by codyhoag** [comment]
I'll resubmit this once I'm finished splitting the article.

**Pull request closed without merging**
