### PR TITLE
LRDOCS-3033 Adaptive Media User Guide

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a  this is for the 7.0 release of Adaptive Media. Please review and send back for holding since this feature is not yet released.

### CODE REVIEW

**Comment by mwilliams2014** [comment]
adding a note to mention the backwards compatibility module.

**Comment by mwilliams2014** [comment]
updated

**Comment by mwilliams2014** [comment]
cc @ngaskill

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Pull request submitted to https://github.com/mwilliams2014/liferay-docs/pull/122. [See changes here.](https://github.com/sez11a/liferay-docs/compare/07d35fae5~2...07d35fae5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Superseded by https://github.com/mwilliams2014/liferay-docs/pull/122

**Comment by sez11a** [comment]
Pull request submitted to https://github.com/mwilliams2014/liferay-docs/pull/123. [See changes here.](https://github.com/sez11a/liferay-docs/compare/07d35fae5~2...07d35fae5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Pull request submitted to https://github.com/mwilliams2014/liferay-docs/pull/124. [See changes here.](https://github.com/sez11a/liferay-docs/compare/07d35fae5~2...07d35fae5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
