### PR TITLE
LRDOCS-7095 UI Concepts

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a this includes @jhinkey 's Architecture intro from this PR (https://github.com/sez11a/liferay-docs/pull/4592) as well.

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Need to update a screenshot before this is merged...working on it now

**Comment by mwilliams2014** [comment]
GTG

**Comment by sez11a** [comment]
@mwilliams2014 Merge conflicted.

**Comment by mwilliams2014** [comment]
Ok @sez11a GTG. Note that the Theme Components and Understanding Page Layout docs are moved to the ui-architecture section as part of this PR. The existing ones were deleted in the PR and will need to be manually removed in KB. Thx!

**Comment by sez11a** [comment]
Just started reviewing :)

**Pull request merged**
