### PR TITLE
LRDOCS-7178 Moving back-end reference articles

### PR DESCRIPTION
**Pull request by ngaskill**
... to parent reference section (back-end section was deleted).

@jhinkey

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @ngaskill this isn't going to work. All these articles must have the 02 prefix, to force the intro to the top.

**Comment by ngaskill** [comment]
@sez11a Jim told me to leave the prefixes off, and that none of the articles in that section should have the prefix.

**Comment by jhinkey** [comment]
@ngaskill - Rich is right. Sorry, I didn't notice how the reference articles were being organized using that convention. It's as Rich says, just add the 02 prefix to the articles.

**Comment by ngaskill** [comment]
@sez11a and @jhinkey : Added the prefixes and merged with master :-)

**Pull request merged**
