### PR TITLE
LRDOCS-6886 Audience Targeting Migration

### PR DESCRIPTION
**Pull request by codyhoag**
Review from sez11a#4214

https://issues.liferay.com/browse/LRDOCS-6886

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
@stephenkostas @codyhoag There's a link at the bottom of the intro to an article called Migrating Behavior-Based Features. Was that one not written?

**Comment by codyhoag** [comment]
@sez11a I wasn't able to find that one. It wasn't in any of the migration docs I'm aware of

**Comment by sez11a** [comment]
@codyhoag Okay; if Steve doesn't respond, I'll just remove the link.

**Comment by codyhoag** [comment]
got it; I'll just remove any links I'm not sure about moving forward. Or at least comment them out.

**Pull request merged**
