### PR TITLE
LPS-102489 Remove unreachable mixins and related function

### PR DESCRIPTION
**Pull request by orsolyalukacs**
Dear @sez11a,

Could you kindly review these changes?
Please feel free to reach out if you have any questions.

Kind regards,
Orsolya

### CODE REVIEW

**Comment by orsolyalukacs** [comment]
Hi @sez11a and @codyhoag,

I think I need to provide some explanation to this.
The changes above only got rid of the error reported by the customer on LPP-35189 and made the button work without the getStateClasses function.

As my understanding mixins are now deprecated, so as create-react-class, also we have migrated away from them and the recommended way is to use React components. 
See here: https://github.com/liferay/alloy-editor/pull/955

I think II'll need to re-send this PR with a reimplementation of the button example and updated related docs.
Am I right?

Thanks for your help in advance,
Orsolya

**Comment by sez11a** [comment]
@mwilliams2014 can you review?

**Comment by mwilliams2014** [comment]
Yes. Checking it out now

**Comment by wincent** [comment]
One thing to note: we did make the mixins available again in this PR:

https://github.com/liferay/alloy-editor/pull/1331

as an escape hatch — they are to be found on `AlloyEditor.Compat.ButtonStateClasses` etc, or at least they will be when we cut the next release of AlloyEditor 2.x —, but we weren't sure whether we wanted to document that. It's basically intended for people who have a bunch of custom buttons using `createClass` if they don't want to rewrite them all using the `AlloyEditor.Base.ButtonStateClasses` (etc). I think that omitting them from the docs is probably the right call for now (although we should document the `AlloyEditor.Base` stuff).

(Speaking of the next AlloyEditor release, we can do that post-SP1; we didn't want to ship a big change right before that.)

**Comment by mwilliams2014** [comment]
Based on @wincent 's comments @orsolyalukacs , I think it is best that we wait for the next version of AlloyEditor to be released soon, and then we can update these docs with the new syntax.

**Comment by orsolyalukacs** [comment]
Thanks @mwilliams2014 and @wincent for your review and comment, I'll close this PR for now, waiting for the release of the new version of AlloyEditor.

**Comment by wincent** [comment]
FYI: published v2.11.0 this morning and sent PR updating liferay-portal "master" to use it:

https://github.com/brianchandotcom/liferay-portal/pull/79280

**Pull request closed without merging**
