### PR TITLE
LRDOCS-5313-and-kids-analytics-cloud

### PR DESCRIPTION
**Pull request by nealrobbins**

### CODE REVIEW

**Comment by nealrobbins** [comment]
https://issues.liferay.com/browse/LRDOCS-5313

**Comment by nealrobbins** [comment]
04-forms-analytics.markdown had some confusion about whether we were counting 
views or submissions (sometimes the heading of section said one thing and the 
body said another). I assumed the heading was correct, but @rbohl  should probably 
check.

**Comment by nealrobbins** [comment]
04-forms-analytics.markdown had some confusion about whether we were counting 
views or submissions (sometimes the heading of section said one thing and the 
body said another). I assumed the heading was correct, but @r should probably 
check.

**Comment by rbohl** [comment]
_Submissions_ is correct. Thanks, Neal!

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
