### PR TITLE
Update 02-configuring-a-liferay-workspace.markdown

### PR DESCRIPTION
**Pull request by jrao**

### CODE REVIEW

**Comment by sez11a** [comment]
@codyhoag: Not that I doubt @jrao at all, but can you verify? :-)

**Comment by codyhoag** [comment]
Sure; I'm taking a look now. The new info is correct, but there is some functionality in that article that it replaces, so I'm doing some restructuring. I'll pull @jrao's commit down and restructure and resend. I'll link here when I'm finished.

**Comment by codyhoag** [comment]
Superseded by sez11a#2447. Thanks, @jrao!

**Comment by sez11a** [comment]
Thanks, @jrao !

**Pull request closed without merging**
