### PR TITLE
Jchoi language

### PR DESCRIPTION
**Pull request by justinchoi001**
Second draft per your revisions. There are two files because I renamed it with a 01 to match the hierarchy; the other file is treated as a deletion or change in github. The image is now a CE image. If it is messy again, please let me know.

### CODE REVIEW

**Comment by sez11a** [comment]
Hey Justin, 

I only see one Markdown file; the other file is the screenshot. But I think you may have committed the wrong one; my wordsmithing commit from https://github.com/justinchoi001/liferay-docs/pull/1/files seems to be missing from the commit history.

**Comment by justinchoi001** [comment]
Hi Rich,

I had to create a new branch because there commit history was getting dirty. What I did was to copy/paste ALL of your wordsmithing into the new branch.

**Comment by sez11a** [comment]
Hey Justin, 

It looks like somehow my changes got lost. I could tell from the first line. I had changed it to this: 

@product@ lets you display content based on language, time zone, "right to left"
(that is, languages such as Hebrew, Arabic, and Persian), and lets you localize
user names and titles.

But you have this: 

@product@ lets you display content based on language, different time zones, "right to left" (that is, languages such as Hebrew, Arabic, and Persian), and localizing user names and titles.

Your first sentence is what you originally had. If you compare the two files, it looks like all my changes got lost.

**Comment by justinchoi001** [comment]
I see why. I must not have included that change because everything else after that has been updated. Let me update that and then push it.

**Comment by justinchoi001** [comment]
Updated: the new commit message is LRDOCS-2733

**Pull request merged**
