### PR TITLE
LRDOCS-3356 blogs unsubscribe by email feature

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a this feature is available in master, and will be available in the next release (7.1). Please review and send back for holding. thx!

cc @sergiogonzalez @4lejandrito

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Need to update once more.

**Comment by mwilliams2014** [comment]
Ready for review

**Comment by sez11a** [comment]
No changes necessary; please just hold on to this one in your branch. Closing this PR.

**Comment by mwilliams2014** [comment]
will do. thx!

**Comment by mwilliams2014** [comment]
cc @ngaskill

**Pull request closed without merging**
