### PR TITLE
LRDOCS-2516 upgrade framework tutorial

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a I have added a temporary intro file here until the other tutorial is written. Then I'll write a proper intro. let me know if that is ok for now, or if I should submit it a different way.

@cgoncas

### CODE REVIEW

**Comment by sez11a** [comment]
@mwilliams2014 you should only submit stuff we can publish, and we can't publish without an intro file. :-(

**Comment by mwilliams2014** [comment]
Sorry @sez11a. I placed a temporary one in there for now. I thought that was how we were doing it. I'll try to write something more fitting before the end of the week and update the pr. The verifier framework tutorial is still being worked on though. Should I hold off on this for now?

**Comment by sez11a** [comment]
Once we removed "draft" from the doc selector, we stopped being able to put in placeholders, temporary files, or anything of the sort. I think there are separate tickets for the verifiers vs the upgrade process; it may be better to write the intro first, add it to this branch, and then work on the verifiers. Then we can at least publish the upgrade process stuff this week and maybe the verifiers next week.

**Comment by mwilliams2014** [comment]
ah, ok. Yeah there are separate tickets. Manuel de la Pena and Cristina González are currently working on the verifiers doc. I can work on the intro this week and add that to this pr. I'll work on the verifiers doc after I get back.

**Comment by mwilliams2014** [comment]
@sez11a Updated intro :-)

**Comment by sez11a** [comment]
Superseded by https://github.com/mwilliams2014/liferay-docs/pull/60

**Pull request closed without merging**
