### PR TITLE
LRDOCS-4063 Fix Overriding Service References

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-4063

### CODE REVIEW

**Comment by jhinkey** [comment]
Miguel, 

Thank you for your fix. I merged in your change and updated the code and tutorial in https://github.com/sez11a/liferay-docs/pull/2641

**Comment by jhinkey** [comment]
Superseded by https://github.com/sez11a/liferay-docs/pull/2641

**Comment by sez11a** [comment]
Did you mean to close this, @jhinkey ? I think you meant to close another PR.

**Comment by jhinkey** [comment]
Oh, you're exactly right. I'll close the other PR. Thanks!

**Pull request merged**
