### PR TITLE
LRDOCS-5347 document polling interval property

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a this includes a gif to clearly illustrate the real time data change in the chart.

cc @jbalsas
cc @julien

### CODE REVIEW

**Comment by sez11a** [comment]
Merge conflicted.

**Comment by mwilliams2014** [comment]
I'll fix and update the pr

**Comment by mwilliams2014** [comment]
@sez11a fixed

**Comment by mwilliams2014** [comment]
One small change to make...

**Comment by mwilliams2014** [comment]
Ok. Fixed the issue

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
