### PR TITLE
LRDOCS-636 Review and wordsmith Configurable Portlet Preferences tutorial

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LRDOCS-636 Review and wordsmith Configurable Portlet Preferences tutorial

### CODE REVIEW

**Comment by sez11a** [comment]
Hey Jesse, I don't think this branch was based on master....

**Comment by jrao** [comment]
@sez11a Sorry, I probably sent it to the wrong branch. Can you merge it into 6.2.x?

**Comment by sez11a** [comment]
So you're saying it's not meant for master?

**Comment by jrao** [comment]
@sez11a Yes. Judging from the commit history, it looks like it's meant for 6.2.x

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Merged into 6.2.x.

**Pull request closed without merging**
