### PR TITLE
LRDOCS-2865, .cfg/.config

### PR DESCRIPTION
**Pull request by rbohl**
DO NOT PUBLISH https://issues.liferay.com/browse/LRDOCS-2865 Changed .cfg to .config where appropriate, made more generalized references where appropriate, and wrapped values in quote marks, where approrpiate.

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @rbohl since this is marked DO NOT PUBLISH, I wanted to let you know it also has a merge conflict. Can you fix and resend? Thanks!

**Comment by rbohl** [comment]
Really? I just merged master into it without trouble.

**Comment by rbohl** [comment]
Fixed merge conflict, @sez11a

**Comment by rbohl** [comment]
Added a note about what versions of CE and DE the .config format applies to. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
View just my changes: https://github.com/sez11a/liferay-docs/compare/rbohl:abf485c829...0fb07ddbd6
View total diff: https://github.com/sez11a/liferay-docs/compare/d200d878e8...0fb07ddbd6

**Pull request closed without merging**
