### PR TITLE
SP-1 | Search Tuning: Synonym Sets | LRDOCS-5909

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-5909, cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Russ @rbohl ,

I believe, we should add a link to https://github.com/sez11a/liferay-docs/blob/72-SP1/en/deployment/articles/03-installing-a-search-engine/03-solr/01-installing-solr-intro.markdown#blacklisting-elasticsearch-only-features from both the Synonyms and Result Rankings docs because after installing SP1 search won't work on deployments using Solr: https://issues.liferay.com/browse/LPS-100156

Sorry, somehow I didn't realize this ticket earlier, though because of this the new search features can be considered as disruptive.

I'll need to update the internal docs and the Support messaging too.

**Comment by rbohl** [comment]
Something like this?

> Search tuning features like Synonym Sets are only supported when using Elasticsearch as the search engine. If you're using Solr, make sure you disable the [search tuning features](/docs/7-2/deploy/-/knowledge_base/d/installing-solr#blacklisting-elasticsearch-only-features)(Synonym
Sets and Result Rankings) if you upgrade your installation to @product@ Service Pack 1 (Fix Pack 2).

**Comment by rbohl** [comment]
We might still have a problem. Though we're adding this important information to both the Installing Solr and Search Tuning docs, what about customers who are already running Solr, and don't care about the Search Tuning features? They won't read either of these articles, and their installation iwll break when they install SP-1/FP-2. So, hopefully we're covering this somewhere in the release docs, too, not just in the official documentation. @lipusz

**Comment by lipusz** [comment]
I'm coordinating with the other SP coordinators to add it to the Important Changes docs too.

**Comment by lipusz** [comment]
Thanks Russ for the prompt actions! :+1: :muscle:

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Merged into https://github.com/sez11a/liferay-docs/tree/72-SP1

**Pull request closed without merging**
