### PR TITLE
LRDOCS-6031 renamed, renumbered, and SF

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a this fixes the numbering which was causing hierarchy nesting issues for 7.1 developing themes docs, as well as adds proper headers for a few articles. This renumbering may require manual deletion of the existing folders/files for front-end development.

### CODE REVIEW

**Comment by sez11a** [comment]
@mwilliams2014 This is merge conflicted. Did you intend to send this to the 7.1 branch?

**Comment by mwilliams2014** [comment]
No, I'm pretty sure this is meant for 7.2, even though I mentioned 7.1 in the comment

**Comment by mwilliams2014** [comment]
I'll try to resolve locally

**Comment by mwilliams2014** [comment]
@sez11a resolved. I'm not sure how, but the files that were conflicted already existed...

**Pull request merged**
