### PR TITLE
Reference 7.1-latest taglib in JSP Overrides tutorial

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jhinkey, as I was reviewing this with @mwilliams2014 the other day, I'd really want us to reword the term `JSP Overrides`. This mechanism does nothing of the sort, and both the title and maybe the content might lead to wrong expectations.

This feature allows the inclusion of code (js, html...) in specifically designed extension points. By no means does this override the original content of the jsp, and developers can throw as many extensions to a single extension point as they wish.

What do you think?

**Comment by mwilliams2014** [comment]
@chema I mentioned this to Jim as part of the updates I'll make for the Dynamic Include tutorial. @jhinkey you can either update it now if you want, or I can update as I work on that. If we want to clear that up asap @jbalsas , then it's probably best for you to clear it up Jim.

**Comment by jhinkey** [comment]
I've updated the titles and made clarifications in the intro and tutorial.

**Comment by jbalsas** [comment]
Awesome! Thanks a lot, @jhinkey!

**Pull request merged**
