### PR TITLE
LRDOCS-3825 image fixing

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-3825 there's a DXP vs. CE difference that wasn't captured in my last pull request. cc @natocesarrego

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hey @rbohl,

The text you've modified in your last pull shouldn't be updated too, in order to reflect the differences between DXP and CE editions?

**Comment by rbohl** [comment]
That's a good question. So the situation right now is that we have one set of articles (in discover/portal/articles) that will populate the customer portal and dev.liferay. We have two different screenshots, and our build script knows how to use the correct screenshot for each site. 

There's one reference to the field type in the text of [Creating Advanced Forms](https://dev.liferay.com/discover/portal/-/knowledge_base/7-0/creating-advanced-forms):

> Combining your form building knowledge with your ability to customize the form layout, build the form to match the screenshot below. It will use paragraph, date, radio, text, and **single checkbox** fields, laid out in two columns.

Because it's only one small reference to the field whose name is changed, I'd rather not change it for the CE article even though it's incorrect, because that means we need to maintain two entirely separate articles (one for DXP and one for CE). @sez11a can correct me if he disagrees, but I'd rather wait and see if we get any negative feedback on the CE article (dev.liferay,com) for referencing an incorrect field name in one place.

**Comment by natocesarrego** [comment]
I see your point, @rbohl. What do you think we change the current text to just mention a few fields and not all of them? Just two or three which are common between the two portal versions. This way we'll fix this issue and also keep a single article. 😉 

By the way, the paragraph field is now Form Text and the radio is named Single Selection. Can you please update it?

I'll wait your considerations.

Thanks in advance.

**Comment by rbohl** [comment]
Oh! I guess I have some refactoring to do. These names must have changed after I documented forms. It's always hard to keep track when you're looking at an unreleased product. Let me talk with Rich when I see him tomorrow, then I'll get back to you.

**Comment by natocesarrego** [comment]
I've imagined this was the cause of this issue and no problem to answer me tomorrow.

Thanks.

**Comment by rbohl** [comment]
@natocesarrego All the other field renames are made in both products, right? CE and DXP?

**Comment by natocesarrego** [comment]
Yeah, only the Multiple Selection field has different labels depending of the portal version.

**Comment by rbohl** [comment]
@sez11a @natocesarrego see the last commit I pushed. Let me know what you think.

**Comment by natocesarrego** [comment]
@rbohl, is missing the renaming of the radio field, which is currently named as single selection. The rest is fine for me. 😉

**Comment by rbohl** [comment]
Interesting, somehow I hadn't committed that one change, though I was sure I made all the field renames at the same time. @sez11a  from the F&W team perspective this is good to go, can be merged. Thanks @natocesarrego

**Pull request merged**
