### PR TITLE
LRDOCS-6317 Handle new header ID syntax

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.liferay.com/browse/LRDOCS-6317

This PR updates our build logic to handle the new header ID syntax.

I've also included the `convert-headers` Ant task, which can be used to convert current legacy headers to the new format. This will be relevant when we decide to backport the parser changes.

Let me know how it looks and if it generates the header ID as you envisioned.

### CODE REVIEW

**Comment by sez11a** [comment]
@codyhoag Why did you use a main class instead of an Ant task for the conversion code?

**Comment by codyhoag** [comment]
@sez11a It was easier to test as a main class. We'll likely remove it once we run it (it's a temporary task; a one time execution), so I didn't bother converting it to an Ant task. I can easily convert it if you want; let me know.

**Comment by codyhoag** [comment]
I guess we were running into issues in other repos with the main class. I'll just convert it to avoid any issues. I'll push up the Ant task in a few minutes.

**Comment by codyhoag** [comment]
@sez11a ok; it's an Ant Task now

**Pull request merged**
