### PR TITLE
LRDOCS-5522 Apio tutorials

### PR DESCRIPTION
**Pull request by ngaskill**

### CODE REVIEW

**Comment by sez11a** [comment]
@ngaskill I don't see my wordsmithing commits from https://github.com/ngaskill/liferay-docs/pull/168

**Comment by ngaskill** [comment]
@sez11a That's because https://github.com/ngaskill/liferay-docs/pull/168 was merged in different branch (LRDOCS-5522-apio). I transferred all that content over manually to a new branch (LRDOCS-5522-apio-new) when the plan was made to transition from a small private alpha to a public beta.

**Comment by sez11a** [comment]
@ngaskill You can't do that, because then you lose history like you have here.

**Comment by ngaskill** [comment]
Sorry :-(

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
