### PR TITLE
LRDOCS-4111 JSDoc Gradle Plugin reference doc

### PR DESCRIPTION
**Pull request by codyhoag**
Resulting from brianchandotcom/liferay-portal#53991

### CODE REVIEW

**Comment by sez11a** [comment]
@codyhoag Merge conflicted.

**Comment by codyhoag** [comment]
@sez11a Fixed!

**Comment by sez11a** [comment]
@codyhoag Ticket is still In Progress by @Ithildir; what should happen with it?

**Comment by codyhoag** [comment]
@sez11a I'm fairly certain he's finished with the plugin. I'll ping him and confirm.

**Comment by codyhoag** [comment]
@sez11a we can close that ticket. It's complete and any further development will be tracked in a different ticket

**Pull request merged**
