### PR TITLE
LRDOCS-4292 Bean Portlets - Portlet 3

### PR DESCRIPTION
**Pull request by jhinkey**
BAG OF HOLDING ITEM

Hi Rich,

This tutorial shouldn't be published until the GA2 release. Thanks.

https://issues.liferay.com/browse/LRDOCS-4292

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Pull request submitted to https://github.com/jhinkey/liferay-docs/pull/419. [See changes here.](https://github.com/sez11a/liferay-docs/compare/e3b35c72c~1...e3b35c72c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Superseded by https://github.com/jhinkey/liferay-docs/pull/419

**Comment by jhinkey** [comment]
Thanks for the corrections and wordsmithing, Rich!

**Pull request closed without merging**
