### PR TITLE
Site management configuration

### PR DESCRIPTION
**Pull request by stephenkostas**
Minimal changes for 7.2. Has been reviewed for accuracy, but almost all files need updated screenshots and links.

02-adding-pages-to-sites needs additional work. The Content Page section is currently in a separate PR: https://github.com/stephenkostas/liferay-docs/pull/77

### CODE REVIEW

**Comment by sez11a** [comment]
@codyhoag Please review

**Comment by codyhoag** [comment]
Review in progress.... Lots of screenshots and updates needed for this one (in particular, articles for pages)

**Comment by codyhoag** [comment]
Sent review sez11a#4241

**Comment by sez11a** [comment]
Thanks, @codyhoag !

**Pull request closed without merging**
