### PR TITLE
LRDOCS-6713 Supporting Custom Content Types

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.liferay.com/browse/LRDOCS-6713

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Hey @codyhoag this is merge conflicted according to GitHub.

**Comment by codyhoag** [comment]
@sez11a Fixed!

**Pull request merged**
