### PR TITLE
LRDOCS-3951 Patching DXP Source Code

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-3951

cc/ @zsoltbalogh

### CODE REVIEW

**Comment by zsoltbalogh** [comment]
cc @ZoltanTakacs - Zoli if you have a chance please also review it.

**Comment by ZoltanTakacs** [comment]
@zsoltbalogh 
Seems good to me. Thanks!

**Comment by jhinkey** [comment]
Thanks, @ZoltanTakacs !

**Comment by zsoltbalogh** [comment]
Thank you, @ZoltanTakacs and @jhinkey!

**Comment by sez11a** [comment]
View total diff: https://github.com/sez11a/liferay-docs/compare/eeec06ab36...9f45519c6d

**Pull request closed without merging**
