### PR TITLE
re-organized search user section

### PR DESCRIPTION
**Pull request by rbohl**
published organization is wrong, so i put all articles (except the section intro) into folders to see if that fixes things.

### CODE REVIEW

**Comment by sez11a** [comment]
@rbohl Seems like all your search stuff is merge conflicted...

**Comment by rbohl** [comment]
argh, i only fixed a link in that article, i believe. sometimes git isn't so smart.

**Comment by rbohl** [comment]
okay, a simple rebase fixed it.

**Comment by sez11a** [comment]
Nope; it's still conflicted.

**Comment by rbohl** [comment]
well, at leas they're different conflicts now :joy:

**Comment by rbohl** [comment]
somehow, I can 
`git pull upstream master`
`git checkout `search-7.2-userGuide-orgnaization`
`git rebase master`
`git push -f origin search-7.2-userGuide-organization`

without problem, and github continues to report conflicts :man_shrugging:

**Comment by rbohl** [comment]
Yep, sent a PR to my own updated master and GitHub doesn't complain.

**Comment by sez11a** [comment]
Just started reviewing :)

**Pull request merged**
