### PR TITLE
LRDOCS-7165 Configurable Fragments and other Echo SP1 features

### PR DESCRIPTION
**Pull request by codyhoag**
These docs must be published for the Liferay 7.2 SP1 release. Thanks!

Summary of SP1 changes:
- New *Making a Fragment Configurable* article
- Added intro section for this article for explanatory text
- New reference article for Fragment configuration JSON examples
- New reference article for escaping Fragment configuration text values
- Resetting web content structure's default values
- Alternative FreeMarker syntax for Fragment HTML
- etc.

https://issues.liferay.com/browse/LRDOCS-7165
https://issues.liferay.com/browse/LRDOCS-7190
https://issues.liferay.com/browse/LRDOCS-7191
https://issues.liferay.com/browse/LRDOCS-7192
https://issues.liferay.com/browse/LRDOCS-7193
https://issues.liferay.com/browse/LRDOCS-7197
https://issues.liferay.com/browse/LRDOCS-7214
https://issues.liferay.com/browse/LRDOCS-7217
https://issues.liferay.com/browse/LRDOCS-7268
https://issues.liferay.com/browse/LRDOCS-7279
https://issues.liferay.com/browse/LRDOCS-7288
https://issues.liferay.com/browse/LRDOCS-7313
https://issues.liferay.com/browse/LRDOCS-7315
https://issues.liferay.com/browse/LRDOCS-7331
https://issues.liferay.com/browse/LRDOCS-7334
https://issues.liferay.com/browse/LRDOCS-7336
https://issues.liferay.com/browse/LRDOCS-7337
https://issues.liferay.com/browse/LRDOCS-7345
https://issues.liferay.com/browse/LRDOCS-7346
https://issues.liferay.com/browse/LRDOCS-7352

### CODE REVIEW

**Comment by codyhoag** [comment]
@sez11a The Echo team is now adding more features into FP1. For simplicity, I'm just going to continue pushing the Echo FP1 content to this branch so you can review/publish in one shot. Let me know if you prefer I break these PRs up instead.

**Comment by codyhoag** [comment]
@sez11a Echo team's FP1 features have been documented. This PR is now ready for review.

**Comment by codyhoag** [comment]
@sez11a The Echo team has decided to hide Fragment Configuration functionality by default (just decided today). I'm asking around for whether we should still publish the feature docs, but the release team doesn't know and most of the Echo team's decision makers are on vacation. I hope to have a definite answer tomorrow.

**Comment by codyhoag** [comment]
@sez11a After confirming with the Echo team this morning, they now want to hold off on publishing these docs on Configurable Fragments until its new target release for SP1. With that said, the priority for this is downgraded and should now be placed in *Bag of Holding* once it has been reviewed. Thanks!

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Merged here: https://github.com/sez11a/liferay-docs/tree/72-SP1

**Pull request closed without merging**
