### PR TITLE
LRDOCS-5413 Gogo Shell portlet

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.liferay.com/browse/LRDOCS-5413

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @codyhoag this is merge conflicted. Plus, can you and @jhinkey work on how upgrades work without the gogo shell, which is a centerpiece of the upgrade docs?

**Comment by codyhoag** [comment]
@sez11a resolved! I'll talk with Jim tomorrow about it.

**Comment by codyhoag** [comment]
@jhinkey this is the PR I was talking about for the Gogo shell updates. Let me know how I can assist.

**Comment by codyhoag** [comment]
@sez11a this PR is good to go. I've updated all non-upgrade articles in our docs to deemphasize use of telnet. Jim will take care of any upgrade-related changes (if any) in a different PR.

**Comment by jhinkey** [comment]
@sez11a I'm confirming with Alberto how this affects the upgrade administrator, if at all.

**Comment by sez11a** [comment]
@jhinkey AFAIK all we have to do is change the instructions and tell them to use the Gogo shell portlet instead of telnetting in, which will be disabled.

**Comment by jhinkey** [comment]
OK. I sent you that text in this PR. https://github.com/sez11a/liferay-docs/pull/3246

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
