### PR TITLE
Unit Testing with JUnit

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-3229

/cc mdelapenya

### CODE REVIEW

**Comment by mdelapenya** [comment]
LGTM

image

**Comment by jhinkey** [comment]
I love the Chuck Norris meme! ... Very strong B-)

**Comment by sez11a** [comment]
Hey @jhinkey , can you replace the IntelliJ screenshot with a Liferay IDE/Developer Studio screenshot?

**Comment by jhinkey** [comment]
Let's revisit this after investigating some more. Thanks.

**Pull request closed without merging**
