### PR TITLE
LRDOCS-3358 freemarker table fix

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a Should be good to go now. The converter is no longer getting hung up, and the render looks correct after using the convert script.

### CODE REVIEW

**Comment by sez11a** [comment]
Uh, nope. Hung my converter and resulted in bad markup again. Weird. Here's the output of my java -version: 

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by sez11a** [comment]
Scratch that last comment; nevermind; you fixed it.

**Comment by sez11a** [comment]
View total diff: https://github.com/sez11a/liferay-docs/compare/fb374487cd...96b6b3e046

**Comment by mwilliams2014** [comment]
Alrightee. Glad that's fixed finally. thx!

**Pull request merged**
