### PR TITLE
LRDOCS-2336 Learning Path updates with new images

### PR DESCRIPTION
**Pull request by stephenkostas**
Fixed the images. Service Builder section still is not ready for review, but everything else should be.

### CODE REVIEW

**Comment by sez11a** [comment]
Still can't build this because of missing images. Please fix. You can test by running `ant dist-ce` from the `develop/tutorials` folder.

**Comment by stephenkostas** [comment]
Okay. It looks like I didn't move all of Mike's images over, but a couple of those are mine to. I'll get it sorted.

**Comment by stephenkostas** [comment]
All of Mike's files which were included in this branch (they possibly should not have been, but they can give you a better idea of the total progress) had been rearranged, so the image tags were one level off in where they should be in the directory structure. I fixed a couple minor additional build issues, so it should all build now.

**Comment by stephenkostas** [comment]
Added the service-builder content. If you're not into it by tomorrow morning, I'll add a screenshot or two and give it an additional review myself.

**Comment by sez11a** [comment]
Superseded by https://github.com/stephenkostas/liferay-docs/pull/8

**Pull request closed without merging**
