### PR TITLE
fix messed up search framework section

### PR DESCRIPTION
**Pull request by rbohl**
hopefully this fixes a problem with headers and folders on portal.dev.liferay.dev in the search dev/frameworks section. cc @lipusz

### CODE REVIEW

**Comment by rbohl** [comment]
Not sure where the conflict comes from. I can rebase this branch on master successfully :confused:

**Comment by rbohl** [comment]
Okay, I used github;s tool, hopefully that fixes it :shipit:

**Comment by sez11a** [comment]
The conflict is likely because I already fixed this in master. You should update your branches more often.... :-)

**Comment by rbohl** [comment]
pretty sure i update master 2-3 times today because of all the merging happening

**Comment by rbohl** [comment]
you're git though, looks good in master :man_shrugging: 

let's close this then and see if the publication fixes the weirdness in the kb ui. if not we can revisit and see if the renumbering helps.

**Comment by sez11a** [comment]
@rbohl You can git blame me. I don't remember when I fixed it.

**Pull request closed without merging**
