### PR TITLE
LRDOCS-5592 7.1 Learning Path: Search and Indexing

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-5592, cc @lipusz I'm sending this in since other writers need the search and indexing code so they can asset enable the entities, but if you have any feedback certainly let me know, and I'll get it in the articles.

### CODE REVIEW

**Comment by lipusz** [comment]
Thanks @rbohl. I'll try to share my notes by end of tomorrow.

**Comment by lipusz** [comment]
08-search-and-indexing/01-enabling-search-and-indexing-for-guestbooks/00-intro.markdown:

1. >In prior versions of @product@, search and indexing was accomplished with one *Indexer class that extended BaseIndexer...

You may want to include something from [Aggregation, Builder and Composition Design Patterns in the new Indexer model in 7.1](https://grow.liferay.com/learn/Composite+Search+Indexer+Implementation+in+7.1#L2.1_Aggregation-Builder-and-Composition-Design-Patterns-in-the-new-Indexer-model-in-7.1) to explain the changes.

The [Old Indexer vs. Composite Indexer Class and Method Mapping](https://grow.liferay.com/learn/Composite+Search+Indexer+Implementation+in+7.1#L2_Old-Indexer-vs-Composite-Indexer-Class-and-Method-Mapping) might also be useful at this point to provide a general overview.

2.
>Since there's no reason to search for guestbooks in the UI, only back-end work is necessary.
I don't understand this. You mean the application does not require UI changes?

TBC.

**Comment by sez11a** [comment]
Hey @rbohl, first, this is merge conflicted. :-p

Second, we should give as much information as it takes for developers to understand what's going on. The complete and full discussion can be in a tutorial, but there should be enough here without glossing it over (we don't want docs that say, "Do this, and it works," without any explanation). We should also link to the full tutorial(s) from here.

**Comment by rbohl** [comment]
superceded: https://github.com/sez11a/liferay-docs/pull/3698

**Pull request closed without merging**
