### PR TITLE
Community theme doc fixes

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a this includes PRS:
https://github.com/liferay/liferay-docs/pull/424
https://github.com/liferay/liferay-docs/pull/425

### CODE REVIEW

**Comment by balcsida** [comment]
Thanks for merging, but did the SF really removed my code? :|

**Comment by mwilliams2014** [comment]
Hey @balcsida, no the SF didn't remove your code. We have a certain syntax we follow for our markdown parser for the documentation which requires the code block to be indented. We also don't indicate the language of the code block above, so I did remove that to comply with our guidelines. Thanks again for bringing it to our attention! without it the code would have been unreadable :-)

**Comment by mwilliams2014** [comment]
Hey @balcsida our Markdown parser will parse it as code and render it as a code block now with the indentation. I think there must have been an issue with extra spaces or tabs being there before. What are you trying to parse it with?

**Comment by balcsida** [comment]
Thank you @mwilliams2014! 🙂

**Comment by balcsida** [comment]
Absolutely fantastic! :)
Thank you!

**Pull request merged**
