### PR TITLE
7.0.x | LRDOCS-5609 OpenID Connect docs

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LRDOCS-5609
Demanded by https://issues.liferay.com/browse/LPS-84026.

Should be published when FP79 will be [released](https://issues.liferay.com/browse/RELEASE-1427).

/cc @ctampoya

### CODE REVIEW

**Comment by lipusz** [comment]
I may need adjust the fix pack version because Brian will need to merge the PR directly to 7.0.x (this can't be delayed to FP80) due to the semver bump it demands on master and 7.1.x.

I'll keep you updated-

**Comment by sez11a** [comment]
@lipusz Does this mean OAuth 2.0 has also been backported to 7.0? If so, we also need to backport those docs....

**Comment by lipusz** [comment]
No, we are bringing back OpenID Connect auth only.

**Comment by lipusz** [comment]
That's why I replaced the link for "OAuth" with the oauth2 site link

**Comment by lipusz** [comment]
Hey Rich, @sez11a 

You can proceed with this I think.

Thanks,
Tibor

**Pull request merged**
