### PR TITLE
LRDOCS-5312 Analytics Cloud: Understanding People

### PR DESCRIPTION
**Pull request by jhinkey**
Here are the articles for section Understanding People. Thanks for all the reviewing!! :-D +1

https://issues.liferay.com/browse/LRDOCS-5312 Learning What Makes Customers Happier
https://issues.liferay.com/browse/LRDOCS-5320 Profiling Individuals
https://issues.liferay.com/browse/LRDOCS-5322 Creating Segments
https://issues.liferay.com/browse/LRDOCS-5426 Profiling Segments
https://issues.liferay.com/browse/LRDOCS-5378 Customer Insights

### CODE REVIEW

**Comment by sez11a** [comment]
@jhinkey Do you want to revisit this branch with regard to figure captions, since they now know how to use our converter?

**Comment by jhinkey** [comment]
@sez11a Yes. I'll take care of those captions now and notify you. Thanks.

**Comment by jhinkey** [comment]
@sez11a I removed the captions workaround last week. These articles are set for your review. Thanks!

**Comment by jhinkey** [comment]
@sez11a OK. The new titles are in here too.

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
