### PR TITLE
LRDOCS-3510 adaptive media thumbnails tutorial

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a please review and send back for holding until this feature is released. thx!

cc @adolfopa

### CODE REVIEW

**Comment by jhinkey** [comment]
I started reviewing.

**Comment by jhinkey** [comment]
@mwilliams2014 - This needs more work, per emailed review. https://issues.liferay.com/browse/LRDOCS-3510.

Note, this tutorial depends on user guide content that hasn't been published. It can't be merged into upstream until that content is present.

**Comment by mwilliams2014** [comment]
@jhinkey, that's why I asked for it to be sent back for holding since the feature hasn't been released. Sorry for any confusion. Thx!

**Comment by mwilliams2014** [comment]
Closing for now. I'll hold until Adaptive Media is released and the User Guide article is ready. Thx!

**Pull request closed without merging**
