### PR TITLE
LRDOCS-5530 7.1 compatibility layer

### PR DESCRIPTION
**Pull request by jbalsas**
@jbalsas I took the information you had drafted here: https://docs.google.com/document/d/16r3_ni7NVLGvpsIpXTZ-Pi2rR7dfwZFHoyewsVoufRY/edit and wrote a tutorial draft. I included it as the last tutorial in the 7.0->7.1 theme upgrade section. Let me know if anything else needs added or if this is good to go. Thanks!

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@sez11a note that these changes are based off of the LRDOCS-5510 theme upgrade tutorial move we discussed, before you had merged it. If you made any changes to that move, let us know so we can resend, otherwise, this PR should be GTG.

**Comment by mwilliams2014** [comment]
@jhinkey @ngaskill

**Comment by sez11a** [comment]
@mwilliams2014 This is merge conflicted, so something must've changed.

**Comment by mwilliams2014** [comment]
Superseded by https://github.com/sez11a/liferay-docs/pull/3478

**Pull request closed without merging**
