### PR TITLE
LRDOCS-6148 Deploying Liferay Portal 7.2

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-6148 Preparing for install
https://issues.liferay.com/browse/LRDOCS-6149 Installing a Liferay Bundle
https://issues.liferay.com/browse/LRDOCS-6156 Installing Liferay on Tomcat
https://issues.liferay.com/browse/LRDOCS-6411 Set the DB server time zone to GMT

### CODE REVIEW

**Comment by david-truong** [comment]
@jhinkey preparing for install sarticle is quite long.  should we considering breaking that article up?

**Comment by jhinkey** [comment]
Sure, I'd be happy to break it up into db and mail setup. thanks

**Comment by jhinkey** [comment]
@david-truong I extracted the mail content to a separate article called _Configuring Mail_

**Comment by jhinkey** [comment]
OK. This one has the metadata commits merged too.

**Comment by sez11a** [comment]
Just started reviewing :)

**Pull request merged**
