### PR TITLE
LRDOCS-5890 Elasticsearch 6.5

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-5890, should publish with FP 5

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @jhinkey this is merge conflicted and the fix pack came out today. Can you fix? @rbohl

**Comment by jhinkey** [comment]
Deconflicting it now. Thanks.

**Comment by jhinkey** [comment]
It's deconflicted and ready to merge. Thanks! cc @rbohl

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Pull request submitted to https://github.com/rbohl/liferay-docs/pull/99. [See changes here.](https://github.com/sez11a/liferay-docs/compare/efe6c81a4~1...efe6c81a4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Superseded by https://github.com/rbohl/liferay-docs/pull/99

**Pull request closed without merging**
