### PR TITLE
Exhaustive list of APIs migrated from core to modules

### PR DESCRIPTION
**Pull request by codyhoag**
@gamerson 

I had Eduardo fill out the remaining services in the Google Doc. I've provided these services in a table, with a brief explanation. Let me know if there is something else that needs to be added to this reference doc. Thanks!

https://issues.liferay.com/browse/LRDOCS-1888

### CODE REVIEW

**Comment by sez11a** [comment]
@gamerson, is this acceptable or do you need more detail?

**Comment by gamerson** [comment]
Nope that should be all the detail I need, because the rest of the "how to fix this" is all the same no matter the migrated api.  Now it would be nice if we had a list of the "module-api" name that you need in order to properly migrate to one of the migrate bundles.  So maybe we can add that to this document as well once we have that information available.  i'll follow up with you guys for more details but this is a great start.

**Comment by codyhoag** [comment]
@gamerson I've updated the list to include the `*-api` and `*-service` modules for all the components. Let me know if you have any further suggestions.

@sez11a I removed the `*Service` suffix for all the API listings, to avoid confusion for developers. Now, only the component entities are listed, which is more generic and less confusing, IMO. Let me know if you have any further suggestions on this topic.

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
