### PR TITLE
Updated twitter widget URL

### PR DESCRIPTION
**Pull request by yadavjpr**
@dejuknow on github deleted 6.2.x branch. Updated correct URL

### CODE REVIEW

**Comment by yadavjpr** [comment]
@sez11a any update on this pull request?

**Comment by sez11a** [comment]
I spoke to @dejuknow and he would rather we find someplace to put it in the liferay-docs repo.

**Comment by dejuknow** [comment]
I'm fine with it linking to my repo, I just can't guarantee that I won't forget again three years down the road and change the path to the file.

**Comment by sez11a** [comment]
Okay, @dejuknow we'll push this through then. :-)

**Pull request merged**
