### PR TITLE
Extending segment criteria (New Dev Topic)

### PR DESCRIPTION
**Pull request by stephenkostas**
https://issues.liferay.com/browse/LRDOCS-6908

### CODE REVIEW

**Comment by stephenkostas** [comment]
There are some links to other sections of the docs that haven't been updated yet.

**Comment by sez11a** [comment]
@codyhoag Please review

**Comment by codyhoag** [comment]
@sez11a Review sent #4233

**Comment by sez11a** [comment]
Thank you, @stephenkostas and @codyhoag !

**Pull request closed without merging**
