### PR TITLE
LRDOCS-4049 server admin

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4049 adapted server administration article for 7.0

### CODE REVIEW

**Comment by sez11a** [comment]
@rbohl should I go over this, or do you still have commits to make?

**Comment by rbohl** [comment]
@sez11a Hold off. I'll let you know when I incorporate the new ImageMagick stuff (this afternoon, likely)

**Comment by rbohl** [comment]
@sez11a All set now. ImageMagick section from LRDOCS-3600 has been incorporated.

**Comment by sez11a** [comment]
Thanks, @rbohl ! 
Superseded by https://github.com/sez11a/liferay-docs/pull/2671

**Pull request closed without merging**
