### PR TITLE
LRDOCS-4070 npm resolver apis

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a I've added an example use case (the main one covered in this section of tutorials). Ultimately, it's up to the developer how they use this info. Ivan likened it to "the same way that you may introspect an OSGi bundle with the `Bundle` interface or the `ClassLoader`…" It's simply an introspection tool that exposes this information. They primarily made the tool to reference package module versions, so they no longer had to hard code the module version number in their portlet's JSPs, but the info can be used for whatever the dev sees fit...

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @mwilliams2014 I assume you're referencing this text: 

```
+exposes an OSGi bundle's npm package descriptors, stored in the `NPMRegistry`, 
 +so you can access them in your server code. This lets you resolve an OSGi 
 +bundle's npm packages and its dependency npm packages and modules in your 
 +npm-based portlets. How you use this information is up to you. For instance, you 
 +can 
 +[reference an OSGi bundle's JavaScript package version number](/develop/tutorials/-/knowledge_base/7-0/obtaining-npm-package-descriptors#using-an-alias-to-reference-a-modules-package) 
 +in your JSP instead of hardcoding it. This makes your code much easier to 
 +maintain since you don't have to update the code each time the module version is 
 +updated. 
```
It's a good start, but I'd like to see more examples of "whatever the dev sees fit." Reading this text brings up a bunch of questions: Is there a best practice here that I should follow? If so, what is it? What happens when I resolve a bundle's packages and then that bundle changes? How do dependencies work? 

Your intro is way too light and doesn't give an overview of what will be discussed, nor does it present a high level picture of the concept and why it's important. I was expecting a re-written intro, not an additional sentence or two.

**Comment by mwilliams2014** [comment]
K. I'll dive deeper into this. Based on what ivan said though, there are not really any other proposed use cases, other than what I said. It's just raw information to be used by the developer.

**Comment by sez11a** [comment]
I understand, and I understand that these things may be covered later, but you never tell the developer that upfront or give him/her an overview of the section or what's coming. That's what I'm looking for.

**Comment by mwilliams2014** [comment]
Yeah. I'm revisiting it now. I've found that I've buried the lead in some cases. I'll reorganize this as you said. Thanks!

**Comment by mwilliams2014** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/2721

**Pull request closed without merging**
