### PR TITLE
https://issues.liferay.com/browse/LRDOCS-1614 Review Ray's OSGi Portlets by example docs and convert to tutorial format

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LRDOCS-1614 Review Ray's OSGi Portlets by example docs and convert to tutorial format

### CODE REVIEW

**Comment by sez11a** [comment]
After reviewing this, @jrao, It looks to me like we've taken parts of this and published it as separate tutorials. Would you agree? If so, I'd like to just close this, as it's been sitting out there for a long time.

**Comment by jrao** [comment]
@sez11a Hi Rich, I agree that these tutorials have all been superceded by more recent tutorials except possibly for this one: https://github.com/jrao/liferay-docs/blob/6ebedda8317a396d1ab86354dc5baccf344c583c/develop/tutorials/articles/modularization-with-osgi-plugins/04-osgi-portlets-mapping-xml-to-properties.markdown

Do you think that one would be useful in the Reference section?

**Comment by sez11a** [comment]
@jrao I think that would be awesome in the reference section, and could be linked to the tutorial on migrating legacy applications: https://github.com/liferay/liferay-docs/blob/master/develop/tutorials/articles/01-introduction-to-liferay-development/08-migrating-legacy-application-to-new-plugins-sdk.markdown

**Comment by jrao** [comment]
Closing this pull since the OSGi properties reference has been merged.

**Pull request closed without merging**
