### PR TITLE
LRDOCS-5584 - Dev Learning Path Through Messages and Errors

### PR DESCRIPTION
**Pull request by stephenkostas**
https://issues.liferay.com/browse/LRDOCS-5584

### CODE REVIEW

**Comment by stephenkostas** [comment]
@nealrobbins

**Comment by stephenkostas** [comment]
@sez11a this has been QAed by @nealrobbins and his feedback has been integrated into this branch.

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
@stephenkostas This PR also contains the Permissions folder. Was it supposed to be there?

**Comment by stephenkostas** [comment]
Yes. I had updated through Permissions.

**Comment by sez11a** [comment]
Superseded by https://github.com/stephenkostas/liferay-docs/pull/50

**Pull request closed without merging**
