### PR TITLE
LRDOCS-5257 editor embed providers tut

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a This also includes LRDOCS-5403

Supersedes https://github.com/sez11a/liferay-docs/pull/3510 

This includes a merge with some of @jbalsas code SF. It appears this also caused a few of the commits to be duplicated. Not sure how to remove those without losing the commit history. Let me know if you want me to resend fresh. Thanks!

### CODE REVIEW

**Comment by sez11a** [comment]
@mwilliams2014 Yeah; can you flatten the commits? I can't tell which files are new.

**Comment by mwilliams2014** [comment]
k, will do.

**Comment by mwilliams2014** [comment]
@sez11a  I removed the duplicated commits. Is that any better, or do you want me to flatten everything into one commit and erase the commit history?

**Comment by mwilliams2014** [comment]
I'll flatten more. I see the confusion with the reorg...just a sec

**Comment by mwilliams2014** [comment]
@sez11a alrightee, should be GTG

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
