### PR TITLE
LRDOCS-3648 Form Navigator Configurations

### PR DESCRIPTION
**Pull request by mwilliams2014**
cc @4lejandrito

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@sez11a I'll make one small update to make sure it is clear that the System Setting allows you to hide form sections and categories only.

**Comment by mwilliams2014** [comment]
@sez11a updated

**Comment by mwilliams2014** [comment]
@sez11a updated

**Comment by sez11a** [comment]
View just my changes: https://github.com/sez11a/liferay-docs/compare/mwilliams2014:9d385a30b2...c8853cd076
View total diff: https://github.com/sez11a/liferay-docs/compare/e43389ef89...c8853cd076

**Pull request closed without merging**
