### PR TITLE
Dxp Build Process

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Rich,

I've completed the DXP build process and have successfully tested it following how I understand it should work. Let me explain briefly....

Due to the fact that we needed to copy over (and combine) our docs into a temporary folder **before** running the `prepare-dist` targets for the `dist` targets, the changes were no longer being made to our actual files, but rather, to temporary files that were eventually deleted. Because of this, I created other ant targets that we can run to update our docs before committing (similar to what most of us do now with the `ant dist` target). This is the brief rationale behind what was done. The following commands are now available:

**Distribution**

- `ant dist-ce`
- `ant dist-dxp`

`dist-ce` works almost identically to the previous `ant-dist`. `dist-dxp` copies over and combines our articles and images found in the new `articles-dxp` and `images-dxp` directories with `articles` and `images`. Both of these targets also replace the `@product_name@` token with the appropriate name.

**Checking/Editing**

- `ant check`
- `ant check-dxp`

These are the targets that we should run before committing our stuff and sending to you/Jim. This will run the `number-headers`, `check-images-site`, `check-intros`, etc. on our current docs that are recognizable by Git (commitable). These are very similar to what `ant dist` used to do, except for the ZIP packaging.

**Individual Checking/Editing**

The individual targets that are run by the `check` targets above follow a similar naming pattern. For example:

*CE*
- `ant check-headers`
- `ant check-images-site`
- `ant check-intros`
- `ant number-headers`
- `ant number-images-site`

*DXP*
- `ant check-headers-dxp`
- `ant check-images-site-dxp`
- `ant check-intros-dxp`
- `ant number-headers-dxp`
- `ant number-images-site-dxp`

*Note:* `ant clean-images` was modified to clean both CE and DXP images at the same time.

Let me know if you have any questions or suggestions. I'll have the token replacements sent to you as soon as I've received them. Thanks!

https://issues.liferay.com/browse/LRDOCS-2322

### CODE REVIEW

**Comment by codyhoag** [comment]
Now that I've slept on this, I have a couple more things I'm going to change. These do not affect the `dist` process, however, (lower priority) and should not stop the merging of this PR (if everything else looks OK).

1. The non-dist `number-headers` task does not replace the tokens for our headers, so they will be generated incorrectly. The `dist-ce` and `dist-dxp` `number-headers` works properly.
2. I did a good deal of hard coding, and would like to specify some terms from a properties file.

I'll work on these when I have time, but these improvements don't affect the time-sensitive DXP build process in any way.

**Comment by codyhoag** [comment]
`number-headers` issue I mentioned in the previous comment is resolved :smile: This prevents headers with tokens from being generated until dist process.

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Excellent job, Cody! Thank you.

**Pull request merged**
