### PR TITLE
Breaking Changes Document

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Rich; as you suggested, I read through the breaking changes to see if any were for internal-use only. I was not able to find any entries that did not affect developers outside Liferay. I coordinated with @jhinkey on a few of the entries, and we decided that the ones I had selected as questionable did indeed affect outside developers. Therefore, I copied over all the contents of the document from `liferay-portal` and removed the guidelines for contributing. Thanks!

### CODE REVIEW

**Comment by sez11a** [comment]
@jorgeferrer can you review and call out anything we shouldn't put in the public document?

**Comment by JorgeFerrer** [comment]
Hey Rich,

I don't think there is anything we should hide.

However, after going over this doc it has reinforced my opinion that it is a bad idea to publish this document which lists all "known" breaking changes. I think it does no good and can do harm. It does no good first because it's not a good idea to go over this list one by one when we have the Migration Tool that points you to the ones the dev is really interested it after analyzing his/her code. It does bad because it will create the sensation that the upgrade will be very hard even if it is not true for your case. Also because it implies that the list is complete but unfortunately it is not the case. 

I think that this document should exist, but not published on LDN, but consumed directly by the Migration Tool.

Thoughts?

**Comment by sez11a** [comment]
That's fine by me: it's an engineering decision. I was assuming that @gamerson's design would allow the tool to pick these up dynamically at runtime if we did it this way, rather than having to embed them in the tool itself, which would necessitate updating the tool every time there's a breaking change. It seems like this is a better design. 

The requirements were: 1) A stable URL, 2) A stable, parseable format, 3) Regular updates of #1 and #2. If we maintain the file, we can definitely achieve all three objectives. If you can achieve that with updates to the other file that @gamerson can consume, then we don't need this file (though I think it would be helpful to developers to publish it and have it indexed). Otherwise, I think we should still publish this.

**Comment by JorgeFerrer** [comment]
Can we achieve that by leaving the doc at a URL (in Github or elsewhere)
that is not linked to from anywhere?

**Pull request merged**
