### PR TITLE
LRDOCS-6088 7.2 osgi cdi integration

### PR DESCRIPTION
**Pull request by jhinkey**
Here's the intro and how to articles for OSGi CDI Integration. Thanks!

https://issues.liferay.com/browse/LRDOCS-6088
https://issues.liferay.com/browse/LRDOCS-4677
https://issues.liferay.com/browse/LRDOCS-4676

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by jhinkey** [comment]
OK. I moved the OSGi CDI integ articles to the DI section. Thanks.

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/jhinkey/liferay-docs/pull/440

**Pull request closed without merging**
