### PR TITLE
LRDOCS-4139 added themes and layout templates section and theme gener…

### PR DESCRIPTION
**Pull request by mwilliams2014**
…ator tutorials

cc @jbalsas

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Includes LRDOCS-4386, LRDOCS-4387, and LRDOCS-4139

**Comment by mwilliams2014** [comment]
@sez11a will resend. An issue has just been brought to my attention.

**Comment by mwilliams2014** [comment]
Resolved

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
