### PR TITLE
LRDOCS-4374, 7.1 Indexing tutorial

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4374, cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Rich @sez11a 

Do you need anything else before publishing this?

Thanks!

**Comment by sez11a** [comment]
@lipusz Yeah; I need to clone myself. Stay tuned....

**Comment by lipusz** [comment]
:smirk:

**Pull request merged**
