### PR TITLE
lrdocs-3307 fix marvel title

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-3307, clarified the title, edited a link, regenerated headers, fixed image paths.

### CODE REVIEW

**Comment by sez11a** [comment]
What's the solr.markdown.orig file that's in this branch?

**Comment by rbohl** [comment]
Sorry, accidentally added that directory with a *wildcard*

**Comment by sez11a** [comment]
Hey @rbohl, another change. Can you revert the header IDs back to their previous values? Otherwise, we'll have to delete the articles and reimport them.

**Comment by rbohl** [comment]
Headers reverted, @sez11a

**Comment by sez11a** [comment]
View just my changes: https://github.com/sez11a/liferay-docs/compare/rbohl:748d6d1cbd...b9ec5ced5b
View total diff: https://github.com/sez11a/liferay-docs/compare/837838c267...b9ec5ced5b

**Pull request closed without merging**
