### PR TITLE
LRDOCS-2642

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/LRDOCS-2642

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Zoli,

I've talked to Zsolt about this section

>A hot fix is provided to a customer when a customer contacts Liferay about an issue, and Liferay’s support team–working with the customer–determines that the problem is indeed an issue with the product that needs to be fixed. Support fixes the bug and provides a hot fix to the customer immediately. This is a short-term fix that solves the issue for the customer as quickly as possible. Hot fixes can patch both the core and the application suites. 

and it should be reworded: hot fixes should be provided only in emergency situations (e.g. to stabilize production system) otherwise customers should use fix packs + MP releases only.

This should be clarified in this section, so they won't expect an intimidate solution on each LESA ticket.

Can you please update it?

@ZoltanTakacs @zsoltbalogh

**Comment by ZoltanTakacs** [comment]
@lipusz would you like to reword this section only for 6.2 or DXP too?

**Comment by lipusz** [comment]
@zsoltbalogh: Zsolt?

On Fri, Jun 17, 2016 at 1:59 PM, Zoltán Takács <notifications@github.com>
wrote:

> @lipusz <https://github.com/lipusz> would you like to reword this section
> only for 6.2 or DXP too?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sez11a/liferay-docs/pull/1695#issuecomment-226751328>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfA4jmsb2j7QPzE_56dENrK8TGFk2K-ks5qMowPgaJpZM4I0ccf>
> .
>



-- 

*Tibor Lipusz*

*Lead Software Engineer @ Platform TS, EMEA*

*SME of Search & Security, Subscription Services, Global*

*LSV Project Lead*


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by zsoltbalogh** [comment]
We should reword only for DXP.

**Comment by ZoltanTakacs** [comment]
@lipusz please send a new PR to master with the updated information for DXP is this pull request is only for 6.2 content.

Thanks,

**Comment by zsoltbalogh** [comment]
We've discussed it with @lipusz that it's the best if two of us work on it @ZoltanTakacs. :)

**Comment by sez11a** [comment]
Hey @zsoltbalogh @lipusz @ZoltanTakacs is this complete?

**Comment by ZoltanTakacs** [comment]
Hi @sez11a,

For 6.2, yes it is.

**Comment by ZoltanTakacs** [comment]
For DXP someone will send you another PR for master.

**Pull request merged**
