### PR TITLE
LRDOCS-4933, form fields reference

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4933, conversion from 7.0 with new fields added.

### CODE REVIEW

**Comment by rbohl** [comment]
cc @jhinkey @ngaskill

**Comment by ngaskill** [comment]
Reviewing

**Comment by ngaskill** [comment]
Wordsmithed and submitted to @jhinkey: https://github.com/jhinkey/liferay-docs/pull/415

**Comment by ngaskill** [comment]
Superseded by https://github.com/sez11a/liferay-docs/pull/3423

**Comment by sez11a** [comment]
@ngaskill Please submit all PRs to me; thank you.

**Pull request closed without merging**
