### PR TITLE
Mentions 6.2.x

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Rich,

Here's the Mentions portlet documentation for 6.2. I also added some images to drawings/ that I used to create the site content for the screenshots.

The app for 6.2 is not yet ready for release. I'll let you know when it's scheduled for release. 

Thanks for reviewing.

### CODE REVIEW

**Comment by sez11a** [comment]
Hey Jim, 

On 6.2.x, there's a limitation where the hyperlink can't be displayed in comments. This needs to be reflected in the docs. 

https://issues.liferay.com/browse/LPS-56020

**Comment by jhinkey** [comment]
OK.  I'll bring that up. Thanks

**Comment by jhinkey** [comment]
Added note on hyperlink limitation.

**Comment by sez11a** [comment]
I spoke to the team this week, and it looks like the 6.2.x version of the Mentions portlet won't see the light of day. I'll leave this open for a little while longer, but you may want to fold anything you have here that's valuable into a 7.0.x branch.

**Comment by jhinkey** [comment]
Ok. I'll put that in there,  Thanks.

**Comment by jhinkey** [comment]
Thanks. I'll work on it here https://github.com/jhinkey/liferay-docs/tree/mentions-7.0.

**Pull request closed without merging**
