### PR TITLE
Product Navigation Dev tutorials

### PR DESCRIPTION
**Pull request by stephenkostas**
Mostly a straight port of the previous content with reorganization and light text editing 
https://issues.liferay.com/browse/LRDOCS-5303
https://issues.liferay.com/browse/LRDOCS-5304
https://issues.liferay.com/browse/LRDOCS-5305
https://issues.liferay.com/browse/LRDOCS-5307
https://issues.liferay.com/browse/LRDOCS-5309

### CODE REVIEW

**Comment by sez11a** [comment]
merge conflicted. Plus I'm confused by the word "previous:" you don't mean 7.0, right?

**Comment by stephenkostas** [comment]
Fixed the conflict.

Finishing up some additional edits before sending up your way for publishing.

**Comment by stephenkostas** [comment]
Did some further editing and added more headings to break up the larger sections. Good for review.

**Comment by nealrobbins** [comment]
@stephenkostas, before I wordsmith this can you rename the product navigation folder and merge master into the branch?
In master, develop/tutorials/articles/ already has folder numbered 260 (import-export-and staging).

**Comment by stephenkostas** [comment]
I updated the folder names and merged in master.

**Comment by nealrobbins** [comment]
Thanks. Superseded by **https://github.com/sez11a/liferay-docs/pull/3397**

**Pull request closed without merging**
