### PR TITLE
LRDOCS-2517 Verifier framework tutorial with verifier clarity

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@sez11a All the information was there. I reorganized the tutorial and added some further explanation for verifiers, so that it would be clearer. 

There is not much more we can provide for verifiers because each verify process is completely different from another: it's totally dependent on the business logic of each application. The integrity rules could force, i.e., all surnames to be uppercase, so the developer would have to create a verify process that updates all rows' surname column. And that will change from application to application.

Hopefully the example provides enough direction for writing a verifier.
Let me know if you think it needs updated. thx!

**Comment by sez11a** [comment]
@mwilliams2014 Not enough clarity. There are no examples given here; we only have a statement that says verifiers ensure database integrity. The example you gave above (making the first letter of all surnames uppercase) doesn't have anything to do with database integrity, but is an example of data cleansing. Database integrity would be making sure all foreign keys point to real records in those other tables and stuff like that. So the reader still has no idea *what to use this for*, which we need to explain. 

Please find some example of a verifier that's currently in Liferay, find out what it does, and use it to explain verifiers, when you would use them, and how you would write one. 

Thanks!

**Comment by mdelapenya** [comment]
Hi @sez11a, saying *database integrity* maybe is not the right word. Maybe we should have chosen *business logic data integrity*, which would have been more precise. And that of course could be checking all journal articles belongs to a group, for instance.

When a verifier is need is something that each application developer must know, because he/she owns the business rules that apply to the data application moves. So we cannot say: _write a verify in `this` concrete case_. We can say _write a verify whenever you must perform data checks and correct them to be compliant with the business rules_. We can share what we do with DDMStructure as example, maybe we can ask that team for the real purpose, but reading the code you can imagine what it does:
- the verifyDDMForm method internally checks that the default language of each DDMForm is present as an available local in the DDMForm, in example. Besides, it checks that all form fields are compliant with some specific rules, present at DDMFormValidatorImpl class.
- the verifyDDMFormLayout internally checks that for all pages, all rows and all columns in a DDMForm, there are no duplicated field names. Besides, it checks that the language if the title of all pages is the same as the DDMFormLayout language. And finally it checks that all columns in all rows in all pages cannot have a size greater than 12.

That for the DDMStructures, but the verifier still performs checks for DDMStructureLinks, DDMTemplateLinks, and DDMContents. But I'm just reading the code. The BusinessProductivity Team could share more input about those verifiers.

Another important thing I would add is that we should avoid saying "_whenever the verifier finds a nonconformity **do that**_". Developers could write a log, or correct the data by themselves with code, or do nothing, or even throw an exception because it's a so critical thing that portal cannot start without it explaining how to correct it manually.

**Comment by mwilliams2014** [comment]
thx @mdelapenya ! I will incorporate this information into the tutorial. I think this explanation will help clear up some confusion and serve as a solid example to show what verifiers can do for an app, and why.

**Pull request closed without merging**
