### PR TITLE
fixed issues and screenshots

### PR DESCRIPTION
**Pull request by stephenkostas**
Fixed instruction issues and added additional screenshots for template steps and intro content

### CODE REVIEW

**Comment by rbohl** [comment]
@stephenkostas @sez11a Is this the branch I should be pulling to do a QA?

**Comment by stephenkostas** [comment]
Yes. That's the one.

**Comment by stephenkostas** [comment]
@sez11a - addressed Russ's comments and completed minor fixes.

**Comment by stephenkostas** [comment]
@mwilliams2014 - should be ready to add video tags and whatnot.

**Comment by mwilliams2014** [comment]
Waiting for @sez11a to do his review before adding those elements, just in case anything changes.

**Comment by sez11a** [comment]
@mwilliams2014 If you're still online, feel free to add the tags.

**Comment by mwilliams2014** [comment]
@sez11a will do!

**Comment by stephenkostas** [comment]
@sez11a - final with video links.

**Comment by mwilliams2014** [comment]
@stephenkostas cc @sez11a Sent https://github.com/stephenkostas/liferay-docs/pull/40 to fix video thumbnail image. Please merge in before publishing. Thanks!

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
