### PR TITLE
LRDOCS-2877 combined social network UserGuide docs and added Social Bookmarks section.

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a  This app hasn't been released yet

supersedes https://github.com/jhinkey/liferay-docs/pull/324

### CODE REVIEW

**Comment by sez11a** [comment]
Which one; social bookmarks?

**Comment by mwilliams2014** [comment]
@sez11a we didn't have social bookmarks documented before. I removed the two separate articles: 'Integrating with Facebook' and 'Integrating with Twitter'. I combined them together, along with the section on social bookmarks, as you suggested.

Is that what you meant?

**Comment by sez11a** [comment]
I'm responding to your comment "This app hasn't been released yet." Are you referring to Social Bookmarks? I'm just trying to determine how to deal with this PR; if I can merge it and publish it or if I need to wait.

**Comment by mwilliams2014** [comment]
Ah ok. Yeah the latest version of social bookmarks for Liferay 7 hasn't been released yet. I'll comment on this pr when the app is ready to be released.

thx!

**Comment by sez11a** [comment]
Wordsmithed and superseded by https://github.com/mwilliams2014/liferay-docs/pull/88

**Pull request closed without merging**
