### PR TITLE
LRDOCS-3573 - Fix SAML and Setting Up SAML articles

### PR DESCRIPTION
**Pull request by justinchoi001**

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @justinchoi001 this one has a merge conflict due to the reorganization to make discover/deployment import more cleanly. Can you fix? Thanks!

**Comment by justinchoi001** [comment]
Hi @sez11a , I'll take care of it.

**Comment by justinchoi001** [comment]
I updated the branch and pushed. Can you see if there are still errors?

**Comment by sez11a** [comment]
View just my changes: https://github.com/sez11a/liferay-docs/compare/justinchoi001:618f89eb98...224fc43708
View total diff: https://github.com/sez11a/liferay-docs/compare/395b8b9c12...224fc43708

**Pull request closed without merging**
