### PR TITLE
LRDOCS-5019, Virtual Instances

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-5019, virtual instances documentation. cc @JorgeFerrer

### CODE REVIEW

**Comment by rbohl** [comment]
testing comment from node gh <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
cc @jhinkey @ngaskill

**Comment by ngaskill** [comment]
Reviewing

**Comment by ngaskill** [comment]
Superseded by https://github.com/sez11a/liferay-docs/pull/3432

**Pull request closed without merging**
