### PR TITLE
Portlet Providers - tutorials

### PR DESCRIPTION
**Pull request by codyhoag**
@juliocamarero

https://issues.liferay.com/browse/LRDOCS-1778
https://issues.liferay.com/browse/LRDOCS-1797

### CODE REVIEW

**Comment by juliocamarero** [comment]
Looks great! I just added a comment about the other method not explained which covers a different use case.

Thanks a lot! :+1:

**Comment by juliocamarero** [comment]
fyi @ealonso

**Comment by codyhoag** [comment]
@juliocamarero Thanks for taking a look! Since the other method is used for a different use case, I was planning on creating another tutorial explaining it. What do you think?

**Comment by codyhoag** [comment]
@juliocamarero I've added to this pull request a tutorial explaining how to use the Portlet Providers framework to generate a portlet ID/URL.

@sez11a Although these two tutorials have some similarities, I think that the different places in which they are used, and the subtle differences on how they can be set up suggests that we write two independent tutorials. Let me know if you have any suggestions on the division of these topics once you begin reviewing. Thanks!

**Comment by juliocamarero** [comment]
Looks really cool @codyhoag :+1:

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
