### PR TITLE
7.0 discover/deployment/ - minor clarifications for installing Tomcat

### PR DESCRIPTION
**Pull request by jhinkey**
cc\ @olafk

### CODE REVIEW

**Comment by sez11a** [comment]
@jhinkey this contains merge-conflict markers in the files. Please fix; thanks!

**Comment by sez11a** [comment]
@jhinkey Still contains merge-conflict markers. Do you plan to update this or send me something new?

**Comment by jhinkey** [comment]
@sez11a I missed your comment earlier. I'll fix the branch and comment back, thanks.

**Comment by jhinkey** [comment]
I'll re-work this and send a new PR

**Pull request closed without merging**
