### PR TITLE
Skinny JSON Provider app

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by jhinkey** [comment]
I converted it to a Tutorial and added a catchy intro.

**Comment by jhinkey** [comment]
Hi Rich. The release had been postponed in December, but is now ready to go live. Anticipating the intended December release, I posted docs at that time to liferay.com at https://www.liferay.com/documentation/liferay-portal/6.2/development/-/ai/invoking-services-using-skinny-json-prov-liferay-portal-6-2-dev-guide-06-en. But I'd rather post the LDN version of it. Can you take a quick look at it and/or give me the go-ahead to publish it to LDN?

The main difference between the LDN version is that it includes a catchy intro.

**Comment by sez11a** [comment]
Just so you know, skinny web is a lab application with no support.

**Comment by jhinkey** [comment]
I added the labs disclaimer to the dev guide content and LDN article.

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
