### PR TITLE
Lrdocs 4070 npm resolver ap is

### PR DESCRIPTION
**Pull request by nealrobbins**
wordsmithing

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@sez11a reminder please send this back for holding and do not publish this yet as the feature has not been released. Thanks!

**Comment by sez11a** [comment]
@mwilliams2014 is this for 7.1 or 7.0?

**Comment by mwilliams2014** [comment]
7.0. Waiting to get confirmation on the proper SP/ FP yet.

**Comment by sez11a** [comment]
Superseded by https://github.com/mwilliams2014/liferay-docs/pull/128

**Pull request closed without merging**
