### PR TITLE
LRDOCS-3248 invitation note

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a app has not been released yet. Please review and send back for holding. thx!

This is an addition to https://github.com/sez11a/liferay-docs/pull/2041 . Since this is for the invitation app and not the Invite Members app, I'm sending this in a separate branch.

### CODE REVIEW

**Comment by sez11a** [comment]
Has merge conflict.

**Comment by mwilliams2014** [comment]
Fixed. Note that this app has not been released as of yet. The only change is the marketplace app note. thx!

**Comment by mwilliams2014** [comment]
@sez11a ready to publish, app has been released. thx!

**Comment by sez11a** [comment]
View total diff: https://github.com/sez11a/liferay-docs/compare/ee1dcfe2d9...fb374487cd

**Pull request closed without merging**
