### PR TITLE
LRDOCS-3360 resource action assignments, and LRDOCS-3568, break up Kaleo Designer article

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-3360 and https://issues.liferay.com/browse/LRDOCS-3568, broke up Kaleo Designer article. @natocesarrego

### CODE REVIEW

**Comment by sez11a** [comment]
View just my changes: https://github.com/sez11a/liferay-docs/compare/rbohl:a4efdd0e49...af2f68c3df
View total diff: https://github.com/sez11a/liferay-docs/compare/74b5f936d0...af2f68c3df

**Comment by natocesarrego** [comment]
Thanks for letting me know about this, @rbohl. I've looked for this update on Customer Portal and LDN, but I couldn't find it. 😞 When will it be published?

Best.

**Comment by rbohl** [comment]
I believe the folks running the customer portal have an automated process that rebuilds the documentation based on liferay-docs master, so I think the answer to your question is "next time the process runs". @sez11a is there anything else we can add to this? Does the process run once per week?

**Comment by sez11a** [comment]
@natocesarrego @rbohl I asked, and yes, it currently runs once a week, on Monday mornings.

**Comment by natocesarrego** [comment]
Nice, @sez11a! Thanks for clarifying this. I've just taken a look and it's already updated. 😄

**Pull request closed without merging**
