### PR TITLE
LRDOCS-4803 Elasticsearch 6 (7.0)

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4803, DO NOT PUBLISH. The FP with ES 6 support should be released this week [CORRECTION: already released, but the MP packages won't be available until Wednesday], so I want to begin getting this reviewed from our side, even while understanding there's still some SME Review left to be done, mainly in the X-Pack Security and X-Pack Monitoring Articles. I know there are still missing links (heh) and other maintenance tasks. I'll be cleaning this up but wanted to get the review started. cc @arboliveira @lipusz

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hi @rbohl 

:+1: In 10-configuring-search.markdown, the name of our ES5 connector will be "Liferay Connector to Elasticsearch 6" according to MP app request google doc https://docs.google.com/document/d/1bNW_5qfaQExmf5_Smaz7FmHx3JFC6SJ8URsF4SHRBVY/edit?ts=5a97360e#heading=h.p57mjufc525x

**Comment by lipusz** [comment]
@rbohl 

:question: `08-liferay-enterprise-search/08-xpack-security.markdown`: It says
>An Enterprise Search-Standard subscription is necessary for this integration.

though our Shield integration is available only for the Premium subscription: https://web.liferay.com/group/customer/dxp/add-ons/enterprise-search

Or did we change our policy with LES2.0?

**Comment by lipusz** [comment]
`08-liferay-enterprise-search/08-xpack-security.markdown`

Code blocks
>./bin/x-pack/certutil ca --pem --ca-dn CN=localhost
and
> ./bin/x-pack/certutil cert --pem --ca-cert /path/to/ca.crt --ca-key /path/to/ca.key --dns localhost --ip 127.0.0.1

are not rendered as computer code.

**Comment by sez11a** [comment]
Pull request submitted to https://github.com/rbohl/liferay-docs/pull/54. [See changes here.](https://github.com/sez11a/liferay-docs/compare/f85f2c696~1...f85f2c696) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Superseded by https://github.com/rbohl/liferay-docs/pull/54

**Comment by lipusz** [comment]
@rbohl 

`08-liferay-enterprise-search/08-xpack-security.markdown`

In 
> 2. Enable TLS on each node via its elasticsearch.yml.

We write 

```
  xpack.ssl.certificate: /path/to/[Elasticsearch Home]/config/instance.crt
  xpack.ssl.key: /path/to/[Elasticsearch Home]/config/instance.key
  xpack.ssl.certificate_authorities: /path/to/ca.crt
```
but then we say
>The example paths above assume you added the certificate to Elasticsearch Home/config/x-pack/.

which is inconsistent especially because we say at the end of step 1 that
>Extract the contents somewhere in the Elasticsearch Home/config folder.

**Comment by lipusz** [comment]
@sez11a Did you reference the right new PR?

**Comment by lipusz** [comment]
@rbohl 

`08-xpack-security.markdown`
The next step after configuring Elasticsearch 6 with X-Pack is

> Configuring the X-Pack Security Adapter 

Two notes: 
* It should say "Liferay X-Pack Security Adapter" or whatever the official name will be
* There is no step to install the adapter. At the beginning of the docs we just say 
>Download and install the [Liferay Connector for X-Pack Security](MP LINK)
but it's not covered what to copy & where. Or we assume they know how to install an app through MP?

**Comment by lipusz** [comment]
@rbohl 

`08-xpack-security.markdown`:

Typo in `transportSSLEnabled=B"true"` That "B" is not necessary I think.

**Comment by lipusz** [comment]
@rbohl 

`08-xpack-security.markdown:`

`password="GqhoaEUyTM@tp1*wQd~F"` Isn't supposed to be `password="liferay"`?

**Comment by rbohl** [comment]
> password="GqhoaEUyTM@tp1*wQd~F" Isn't supposed to be password="liferay"?

@lipusz since I demonstrated using the `setup-passwords auto` command, I used the auto-generated password here. I guess that's not consistent with the monitoring docs though, where we use `liferay`. Perhaps I should point out in the monitoring article that the password will be whatever they set the password to, and that they can change it once Kibana is up and running.

**Comment by rbohl** [comment]
@lipusz 

> There is no step to install the adapter. At the beginning of the docs we just say ...  but it's not covered what to copy & where. Or we assume they know how to install an app through MP?

Yeah I thin that we should cover this or at least link tot eh MP docs. However, now I remember Shield and Marvel weren't on MP. I guess the same will be true for the X-Pack connectors?

**Comment by nicolelau** [comment]
@rbohl - The X-Pack connectors will have entries on MP, but will only be available for download on https://web.liferay.com/group/customer/dxp/downloads/enterprise-search. The actual download will look just like a regular lpkg from Marketplace.

**Pull request closed without merging**
