### PR TITLE
Tutorial on overriding Liferay's services

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-1885

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Never mind. :-)

**Comment by rbohl** [comment]
Updated to use Blade Tools. Ready for Review. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sez11a** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
Examples added to intro, and tried to make clear why a dev would want to use this functionality. Let me know if it needs anything else. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
You might recognize one of the examples I used :)

**Pull request merged**
